apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - router-api.yaml
  - admin-api.yaml
  - order-agent.yaml
  - appointment-agent.yaml
  - credit-card-repayment-agent.yaml
  - gas-bill-agent.yaml
  - forex-agent.yaml
  - chat-web.yaml
  - admin-web.yaml
  - ingress.yaml
