from __future__ import annotations

from decimal import Decimal, InvalidOperation
from typing import Any

from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, ConfigDict, Field

from .slot_utils import SlotDefinition, SlotValueType, slot_value_grounded
from .support import (
    AgentConversationContext,
    AgentCustomer,
    AgentExecutionResponse,
    AgentIntentContext,
    ConfigVariablesRequest,
    JsonObjectRunner,
    dump_json,
)


class TransferPayer(BaseModel):
    """Optional payer-side transfer slots passed from the router."""

    model_config = ConfigDict(populate_by_name=True)

    card_no: str | int | None = Field(default=None, alias="cardNo")
    card_remark: str | None = Field(default=None, alias="cardRemark")


class TransferPayee(BaseModel):
    """Payee-side transfer slots passed from the router."""

    model_config = ConfigDict(populate_by_name=True)

    name: str | None = Field(default=None, alias="name")
    card_no: str | int | None = Field(default=None, alias="cardNo")
    card_remark: str | None = Field(default=None, alias="cardRemark")
    card_bank: str | None = Field(default=None, alias="cardBank")
    phone: str | int | None = Field(default=None, alias="phone")


class TransferDetails(BaseModel):
    """Amount-side transfer slots passed from the router."""

    model_config = ConfigDict(populate_by_name=True)

    amount: str | int | float | None = Field(default=None, alias="amount")
    ccy: str | None = Field(default=None, alias="ccy")


class TransferMoneyAgentRequest(ConfigVariablesRequest):
    """Agent request payload generated by the router field mapping."""

    model_config = ConfigDict(populate_by_name=True)

    customer: AgentCustomer = Field(default_factory=AgentCustomer)
    conversation: AgentConversationContext = Field(default_factory=AgentConversationContext)
    intent: AgentIntentContext = Field(default_factory=AgentIntentContext)
    payer: TransferPayer = Field(default_factory=TransferPayer)
    payee: TransferPayee = Field(default_factory=TransferPayee)
    transfer: TransferDetails = Field(default_factory=TransferDetails)

    def slot_value(self, name: str, fallback: Any = None) -> Any:
        slots_data = self.get_slots_data()
        if name in slots_data:
            return slots_data.get(name)
        return fallback

    def intent_context(self) -> AgentIntentContext:
        parsed = self.get_config_json_value("intent")
        if isinstance(parsed, dict):
            try:
                return AgentIntentContext.model_validate(parsed)
            except Exception:
                pass
        return self.intent

    def recent_messages(self) -> list[str]:
        parsed = self.get_config_json_value("recent_messages")
        if isinstance(parsed, list):
            return [str(item) for item in parsed]
        return list(self.conversation.recent_messages)

    def long_term_memory_items(self) -> list[str]:
        parsed = self.get_config_json_value("long_term_memory")
        if isinstance(parsed, list):
            return [str(item) for item in parsed]
        return list(self.conversation.long_term_memory)


class TransferMoneyResolution(BaseModel):
    """Normalized transfer slot state used for execution or follow-up prompts."""

    amount: str | None = None
    ccy: str | None = None
    payer_card_no: str | None = None
    payer_card_remark: str | None = None
    payee_name: str | None = None
    payee_card_no: str | None = None
    payee_card_remark: str | None = None
    payee_card_bank: str | None = None
    payee_phone: str | None = None
    has_enough_information: bool = False
    ask_message: str = "请提供金额、收款人姓名"


_AMOUNT_SLOT = SlotDefinition(slot_key="amount", value_type=SlotValueType.CURRENCY)
_CCY_SLOT = SlotDefinition(slot_key="ccy", value_type=SlotValueType.STRING, aliases=["币种", "货币"])
_PAYER_CARD_NO_SLOT = SlotDefinition(
    slot_key="payer_card_no",
    value_type=SlotValueType.STRING,
    aliases=["付款卡", "付款卡号", "付款卡尾号"],
)
_PAYER_CARD_REMARK_SLOT = SlotDefinition(
    slot_key="payer_card_remark",
    value_type=SlotValueType.STRING,
    aliases=["付款卡备注", "付款账户备注"],
)
_PAYEE_NAME_SLOT = SlotDefinition(
    slot_key="payee_name",
    value_type=SlotValueType.STRING,
    aliases=["收款人姓名", "收款人", "对方姓名"],
)
_PAYEE_CARD_NO_SLOT = SlotDefinition(
    slot_key="payee_card_no",
    value_type=SlotValueType.STRING,
    aliases=["收款卡号", "收款卡尾号", "收款卡卡号/尾号", "对方卡号", "对方卡尾号"],
)
_PAYEE_CARD_REMARK_SLOT = SlotDefinition(
    slot_key="payee_card_remark",
    value_type=SlotValueType.STRING,
    aliases=["收款卡备注", "收款账户备注"],
)
_PAYEE_CARD_BANK_SLOT = SlotDefinition(
    slot_key="payee_card_bank",
    value_type=SlotValueType.STRING,
    aliases=["收款银行", "收款卡银行"],
)
_PAYEE_PHONE_SLOT = SlotDefinition(
    slot_key="payee_phone",
    value_type=SlotValueType.STRING,
    aliases=["收款手机号", "收款手机号尾号", "收款手机号/尾号"],
)


TRANSFER_MONEY_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            (
                "你是银行转账场景里的业务槽位填充器。"
                "上游已经把请求路由到了 transfer_money。"
                "你不做意图识别，不执行转账，只做槽位提取和下一步追问。"
                "你必须只输出 JSON，不能输出解释。"
                "当前任务只关心这些业务槽位：amount、payer_card_no、payer_card_remark、"
                "payee_name、payee_card_no、payee_card_remark、payee_card_bank、payee_phone。"
                "其中 amount、payee_name 是必填。"
                "规则："
                "1. 优先保留 current_slots 里已经确认的值；当前输入只补充缺失槽位时，不能重置已有槽位。"
                "2. 只有用户明确修正某个槽位时，才覆盖那个槽位。"
                "3. payee_name 只承载收款人姓名；例如“给小红转200”时，应返回 payee_name='小红'。"
                "4. payee_card_no 只承载收款卡卡号或尾号；例如“收款卡尾号1234”时，应返回 payee_card_no='1234'。"
                "5. amount 只保留数值字符串；如“转500”“500块”“500元”都应提取为 amount='500'。"
                "6. payer_card_no、payer_card_remark、payee_card_no、payee_card_remark、payee_card_bank、payee_phone 都是可选槽位，"
                "只有用户明确提供时才提取。"
                "7. recent_messages 和 long_term_memory 只能帮助你理解用户是不是在补充当前转账任务，"
                "不能把历史里出现过但当前轮没有再次明确提供的新槽位直接当成当前确认输入。"
                "8. 如果信息不足，has_enough_information 必须为 false，并给出简洁明确的 ask_message。"
                "9. ask_message 只追问当前缺失的必填槽位，不要追问可选槽位。"
                "示例："
                "A. 首轮输入“给小红转500”时，应返回 payee_name='小红'、amount='500'，且 has_enough_information=true。"
                "B. 首轮输入“给尾号1234那张卡转200”时，应返回 payee_card_no='1234'、amount='200'，同时因为 payee_name 缺失而继续追问。"
                "C. current_slots 已有 payee_name='小红'、amount='500'，current_input='收款卡尾号1234' 时，应补 payee_card_no='1234'。"
                "D. current_slots 已有 amount='500'，current_input='付款卡备注工资卡' 时，应补 payer_card_remark='工资卡'。"
            ),
        ),
        (
            "human",
            (
                "intent(JSON):\n{intent_json}\n\n"
                "current_input:\n{input_text}\n\n"
                "current_slots(JSON):\n{current_slots_json}\n\n"
                "recent_messages(JSON):\n{recent_messages_json}\n\n"
                "long_term_memory(JSON):\n{long_term_memory_json}\n\n"
                "请返回 JSON:\n"
                "{{\n"
                '  "amount": "string | null",\n'
                '  "payer_card_no": "string | null",\n'
                '  "payer_card_remark": "string | null",\n'
                '  "payee_name": "string | null",\n'
                '  "payee_card_no": "string | null",\n'
                '  "payee_card_remark": "string | null",\n'
                '  "payee_card_bank": "string | null",\n'
                '  "payee_phone": "string | null",\n'
                '  "has_enough_information": true,\n'
                '  "ask_message": "string"\n'
                "}}"
            ),
        ),
    ]
)


class TransferMoneyAgentService:
    """Defensive slot validator and executor for transfer_money."""

    def __init__(self, *, resolver: JsonObjectRunner | None = None) -> None:
        self.resolver = resolver

    async def handle(self, request: TransferMoneyAgentRequest) -> AgentExecutionResponse:
        """Resolve transfer slots, ask for required fields when needed, then simulate execution."""
        input_text = request.txt.strip()
        intent_context = request.intent_context()
        recent_messages = request.recent_messages()
        long_term_memory = request.long_term_memory_items()
        seeded = TransferMoneyResolution(
            amount=self._normalize_amount(request.slot_value("amount", request.transfer.amount)),
            ccy=self._normalize_ccy(request.slot_value("ccy", request.transfer.ccy)),
            payer_card_no=self._normalize_text(request.slot_value("payer_card_no", request.payer.card_no)),
            payer_card_remark=self._normalize_text(
                request.slot_value("payer_card_remark", request.payer.card_remark)
            ),
            payee_name=self._normalize_text(request.slot_value("payee_name", request.payee.name)),
            payee_card_no=self._normalize_text(request.slot_value("payee_card_no", request.payee.card_no)),
            payee_card_remark=self._normalize_text(
                request.slot_value("payee_card_remark", request.payee.card_remark)
            ),
            payee_card_bank=self._normalize_text(request.slot_value("payee_card_bank", request.payee.card_bank)),
            payee_phone=self._normalize_phone(request.slot_value("payee_phone", request.payee.phone)),
        )
        direct_resolution = self._finalize_resolution(seeded, TransferMoneyResolution())
        if not input_text and direct_resolution.has_enough_information:
            resolution = direct_resolution
        else:
            resolution = await self._resolve(
                request,
                seeded,
                intent_context=intent_context,
                recent_messages=recent_messages,
                long_term_memory=long_term_memory,
            )

        slot_memory = self._slot_memory(resolution)
        missing_fields = self._missing_fields(resolution)
        payload = {
            "agent": "transfer_money",
            "amount": resolution.amount,
            "ccy": resolution.ccy,
            "payer_card_no": resolution.payer_card_no,
            "payer_card_remark": resolution.payer_card_remark,
            "payee_name": resolution.payee_name,
            "payee_card_no": resolution.payee_card_no,
            "payee_card_remark": resolution.payee_card_remark,
            "payee_card_bank": resolution.payee_card_bank,
            "payee_phone": resolution.payee_phone,
        }

        if missing_fields:
            return AgentExecutionResponse.waiting(
                resolution.ask_message or self._ask_message(missing_fields),
                hand_over_reason="missing_required_slots",
                data=self._response_data(resolution),
                slot_memory=slot_memory,
                payload={**payload, "missing_fields": missing_fields},
            )

        amount_value = self._amount_value(resolution.amount)
        if amount_value is not None and amount_value > Decimal("8000"):
            return AgentExecutionResponse(
                event="final",
                content="账户余额不足",
                ishandover=True,
                isHandOver=True,
                handOverReason="insufficient_balance",
                status="failed",
                data=self._response_data(resolution),
                slot_memory=slot_memory,
                payload={**payload, "business_status": "insufficient_balance", "balance": 8000},
            )

        amount_text = resolution.amount or "0"
        ccy_text = resolution.ccy or "CNY"
        payee_text = resolution.payee_name or resolution.payee_card_no or "收款人"
        return AgentExecutionResponse.completed(
            f"已受理向{payee_text}转账 {amount_text} {ccy_text}，等待助手确认完成态",
            hand_over_reason="等待助手确认完成态",
            data=self._response_data(resolution),
            slot_memory=slot_memory,
            payload={**payload, "business_status": "success"},
            completion_state=1,
            completion_reason="agent_partial_done",
        )

    def _response_data(self, resolution: TransferMoneyResolution) -> list[dict[str, str]]:
        """Build the transfer summary payload expected by the assistant-facing protocol."""
        if resolution.amount is None and resolution.payee_name is None:
            return []
        return [
            {
                "isSubAgent": "True",
                "typIntent": "mbpTransfer",
                "answer": (
                    f"||{'' if resolution.amount is None else resolution.amount}"
                    f"|{'' if resolution.payee_name is None else resolution.payee_name}|"
                ),
            }
        ]

    async def _resolve(
        self,
        request: TransferMoneyAgentRequest,
        seeded: TransferMoneyResolution,
        *,
        intent_context: AgentIntentContext,
        recent_messages: list[str],
        long_term_memory: list[str],
    ) -> TransferMoneyResolution:
        """Use the optional LLM resolver to supplement missing transfer slots."""
        if self.resolver is None:
            return self._finalize_resolution(seeded, TransferMoneyResolution())

        try:
            raw_payload = await self.resolver.run_json(
                prompt=TRANSFER_MONEY_PROMPT,
                variables={
                    "intent_json": dump_json(intent_context.model_dump()),
                    "input_text": request.txt,
                    "current_slots_json": dump_json(
                        {
                            "amount": seeded.amount,
                            "ccy": seeded.ccy,
                            "payer_card_no": seeded.payer_card_no,
                            "payer_card_remark": seeded.payer_card_remark,
                            "payee_name": seeded.payee_name,
                            "payee_card_no": seeded.payee_card_no,
                            "payee_card_remark": seeded.payee_card_remark,
                            "payee_card_bank": seeded.payee_card_bank,
                            "payee_phone": seeded.payee_phone,
                        }
                    ),
                    "recent_messages_json": dump_json(recent_messages),
                    "long_term_memory_json": dump_json(long_term_memory),
                },
                schema=TransferMoneyResolution,
            )
            resolved = TransferMoneyResolution.model_validate(raw_payload)
        except Exception:
            resolved = TransferMoneyResolution()

        self._drop_unconfirmed_history_values(request, seeded, resolved)
        return self._finalize_resolution(seeded, resolved)

    def _drop_unconfirmed_history_values(
        self,
        request: TransferMoneyAgentRequest,
        seeded: TransferMoneyResolution,
        resolved: TransferMoneyResolution,
    ) -> None:
        """Drop values that are not grounded in the current input text."""
        if resolved.payee_name and resolved.payee_name != seeded.payee_name:
            if not slot_value_grounded(
                slot_def=_PAYEE_NAME_SLOT,
                value=resolved.payee_name,
                grounding_text=request.txt,
            ):
                resolved.payee_name = None
        if resolved.amount and resolved.amount != seeded.amount:
            if not slot_value_grounded(slot_def=_AMOUNT_SLOT, value=resolved.amount, grounding_text=request.txt):
                resolved.amount = None
        if resolved.ccy and resolved.ccy != seeded.ccy:
            if not slot_value_grounded(slot_def=_CCY_SLOT, value=resolved.ccy, grounding_text=request.txt):
                resolved.ccy = None
        if resolved.payer_card_no and resolved.payer_card_no != seeded.payer_card_no:
            if not slot_value_grounded(
                slot_def=_PAYER_CARD_NO_SLOT,
                value=resolved.payer_card_no,
                grounding_text=request.txt,
            ):
                resolved.payer_card_no = None
        if resolved.payer_card_remark and resolved.payer_card_remark != seeded.payer_card_remark:
            if not slot_value_grounded(
                slot_def=_PAYER_CARD_REMARK_SLOT,
                value=resolved.payer_card_remark,
                grounding_text=request.txt,
            ):
                resolved.payer_card_remark = None
        if resolved.payee_card_no and resolved.payee_card_no != seeded.payee_card_no:
            if not slot_value_grounded(
                slot_def=_PAYEE_CARD_NO_SLOT,
                value=resolved.payee_card_no,
                grounding_text=request.txt,
            ):
                resolved.payee_card_no = None
        if resolved.payee_card_remark and resolved.payee_card_remark != seeded.payee_card_remark:
            if not slot_value_grounded(
                slot_def=_PAYEE_CARD_REMARK_SLOT,
                value=resolved.payee_card_remark,
                grounding_text=request.txt,
            ):
                resolved.payee_card_remark = None
        if resolved.payee_card_bank and resolved.payee_card_bank != seeded.payee_card_bank:
            if not slot_value_grounded(
                slot_def=_PAYEE_CARD_BANK_SLOT,
                value=resolved.payee_card_bank,
                grounding_text=request.txt,
            ):
                resolved.payee_card_bank = None
        if resolved.payee_phone and resolved.payee_phone != seeded.payee_phone:
            if not slot_value_grounded(
                slot_def=_PAYEE_PHONE_SLOT,
                value=resolved.payee_phone,
                grounding_text=request.txt,
            ):
                resolved.payee_phone = None

    def _finalize_resolution(
        self,
        seeded: TransferMoneyResolution,
        resolved: TransferMoneyResolution,
    ) -> TransferMoneyResolution:
        """Merge seeded slots with the latest resolved slots and compute prompt state."""
        amount = self._normalize_amount(resolved.amount) or seeded.amount
        ccy = self._normalize_ccy(resolved.ccy) or seeded.ccy
        payer_card_no = self._normalize_text(resolved.payer_card_no) or seeded.payer_card_no
        payer_card_remark = self._normalize_text(resolved.payer_card_remark) or seeded.payer_card_remark
        payee_name = self._normalize_text(resolved.payee_name) or seeded.payee_name
        payee_card_no = self._normalize_text(resolved.payee_card_no) or seeded.payee_card_no
        payee_card_remark = self._normalize_text(resolved.payee_card_remark) or seeded.payee_card_remark
        payee_card_bank = self._normalize_text(resolved.payee_card_bank) or seeded.payee_card_bank
        payee_phone = self._normalize_phone(resolved.payee_phone) or seeded.payee_phone

        merged = TransferMoneyResolution(
            amount=amount,
            ccy=ccy,
            payer_card_no=payer_card_no,
            payer_card_remark=payer_card_remark,
            payee_name=payee_name,
            payee_card_no=payee_card_no,
            payee_card_remark=payee_card_remark,
            payee_card_bank=payee_card_bank,
            payee_phone=payee_phone,
        )
        missing_fields = self._missing_fields(merged)
        ask_message = (resolved.ask_message or "").strip()
        if missing_fields:
            ask_message = ask_message or self._ask_message(missing_fields)

        return TransferMoneyResolution(
            amount=amount,
            ccy=ccy,
            payer_card_no=payer_card_no,
            payer_card_remark=payer_card_remark,
            payee_name=payee_name,
            payee_card_no=payee_card_no,
            payee_card_remark=payee_card_remark,
            payee_card_bank=payee_card_bank,
            payee_phone=payee_phone,
            has_enough_information=not missing_fields,
            ask_message=ask_message,
        )

    def _normalize_text(self, value: str | int | None) -> str | None:
        """Normalize generic text slots while preserving business wording."""
        if value is None:
            return None
        stripped = str(value).strip()
        return stripped or None

    def _normalize_amount(self, value: str | int | float | None) -> str | None:
        """Normalize amount-like inputs into canonical decimal strings."""
        if value is None:
            return None
        digits: list[str] = []
        dot_seen = False
        for character in str(value):
            if character.isdigit():
                digits.append(character)
                continue
            if character == "." and not dot_seen:
                digits.append(character)
                dot_seen = True
        normalized = "".join(digits).strip(".")
        if not normalized:
            return None
        try:
            amount = Decimal(normalized)
        except InvalidOperation:
            return None
        if amount == amount.to_integral():
            return format(amount.quantize(Decimal("1")), "f")
        return format(amount.normalize(), "f")

    def _normalize_ccy(self, value: str | None) -> str | None:
        """Normalize common currency names into short codes when possible."""
        normalized = self._normalize_text(value)
        if normalized is None:
            return None
        mapping = {
            "人民币": "CNY",
            "cny": "CNY",
            "美元": "USD",
            "usd": "USD",
            "港币": "HKD",
            "港元": "HKD",
            "hkd": "HKD",
            "欧元": "EUR",
            "eur": "EUR",
            "日元": "JPY",
            "jpy": "JPY",
        }
        return mapping.get(normalized.lower(), normalized.upper() if normalized.isascii() else normalized)

    def _normalize_phone(self, value: str | int | None) -> str | None:
        """Normalize phone-like inputs into digit-only strings."""
        if value is None:
            return None
        digits = "".join(character for character in str(value) if character.isdigit())
        return digits or self._normalize_text(value)

    def _amount_value(self, value: str | None) -> Decimal | None:
        """Convert the normalized amount back into a Decimal for business checks."""
        if value is None:
            return None
        try:
            return Decimal(value)
        except InvalidOperation:
            return None

    def _missing_fields(self, resolution: TransferMoneyResolution) -> list[str]:
        """Return the required fields still missing for execution."""
        missing: list[str] = []
        if not resolution.amount:
            missing.append("amount")
        if not resolution.payee_name:
            missing.append("payee_name")
        return missing

    def _ask_message(self, missing_fields: list[str]) -> str:
        """Build the follow-up prompt for the currently missing required slots."""
        labels = {
            "amount": "金额",
            "payee_name": "收款人姓名",
        }
        if not missing_fields:
            return ""
        return "请提供" + "、".join(labels[field] for field in missing_fields)

    def _slot_memory(self, resolution: TransferMoneyResolution) -> dict[str, Any]:
        """Project the normalized resolution into router-visible slot memory."""
        slot_memory: dict[str, Any] = {}
        if resolution.amount:
            slot_memory["amount"] = resolution.amount
        if resolution.payer_card_no:
            slot_memory["payer_card_no"] = resolution.payer_card_no
        if resolution.payer_card_remark:
            slot_memory["payer_card_remark"] = resolution.payer_card_remark
        if resolution.payee_name:
            slot_memory["payee_name"] = resolution.payee_name
        if resolution.payee_card_no:
            slot_memory["payee_card_no"] = resolution.payee_card_no
        if resolution.payee_card_remark:
            slot_memory["payee_card_remark"] = resolution.payee_card_remark
        if resolution.payee_card_bank:
            slot_memory["payee_card_bank"] = resolution.payee_card_bank
        if resolution.payee_phone:
            slot_memory["payee_phone"] = resolution.payee_phone
        return slot_memory
