apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-order-agent
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-appointment-agent
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-credit-card-agent
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-gas-bill-agent
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-forex-agent
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-fallback-agent
spec:
  replicas: 0
